#initial settings
setup:
    name: Linear
    output_path: output/
    trainModel: true
dataset:    
    folder: ./data/Linear/
    pre_processed: [BP-05~32_refScalp_eventLoc-speech~speech~focus_S1_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S2_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S3_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S4_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S5_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S6_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S7_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S8_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S9_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S10_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S11_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S12_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S14_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S15_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S16_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S17_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S18_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S19_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S20_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S21_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S22_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S23_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S24_data_preproc.mat, BP-05~32_refScalp_eventLoc-speech~speech~focus_S25_data_preproc.mat]
    scaler:
        type: RobustScaler
        feature_range: [-1,1]
        path: ./data/Linear/EventAAD_part3_RobustScaler.scl
        
    all_sbjs: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
    from_sbj: 0
    to_sbj: 3
    channels: ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FC5', 'FC1', 'FC2', 'FC6', 'M1', 'T7', 'C3', 'Cz', 'C4', 'T8', 'M2', 'CP5', 'CP1', 'CP2', 'CP6', 'P7', 'P3', 'Pz', 'P4', 'P8', 'POz', 'O1', 'Oz', 'O2'] # EventAAD
    eeg_context: 0.4
    sr: 64
    windows: [1.2]

model:
    tag: Linear
    model_name: Linear